### PR TITLE
Fix issue 4431 : hide hotel if price is 0

### LINKED ISSUE #4431: [Travel] $0 hotels on the detail page
**Describe the bug**
$0 hotels can be found on the detail page.

**Steps To Reproduce**
1. Go to 'Travel vertical'
2. Click on 'Budapest'
3. Scroll down to 'Top hotels'
4. Found a hotel with $0 as following

**Screenshots/videos**
image

**Device info (please complete the following information):**
 - Device: [e.g. Samsung A50]
 - Webview [e.g. 78.0.3904.108]
 - Version [e.g. 2.0.3(17314).beta]

**Reproduce rate**
every time

### PR DESCRIPTION
**Pull request by kinse**
Fix #4431

### CODE REVIEW

File: app/src/main/java/org/mozilla/rocket/content/travel/ui/TravelCityViewModel.kt [hunk 1]
```diff
@@ -148,9 +148,9 @@ class TravelCityViewModel(
         if (hotelResult is Result.Success) {
             hotelsCount += hotelResult.data.result.size
             data.addAll(
-                hotelResult.data.result.filterNotNull().map {
-                    TravelMapper.toHotelUiModel(it)
-                }
+                hotelResult.data.result.filterNotNull()
+                    .filter { it.price != 0f }
```
Comment (hartsu) [inline app/src/main/java/org/mozilla/rocket/content/travel/ui/TravelCityViewModel.kt]: How about use it.price > 0f to avoid unexpected negative price case?
