### PR TITLE
[Travel] Wiki support Chinese parenthesis

### LINKED ISSUE #4512: Remove the content in "()" in the Wikipedia card.
**Describe the bug**
Remove the content in "()" in Wikipedia cards (expecially in Chinese version).

### PR DESCRIPTION
**Pull request by kinse**
Close #4512

### CODE REVIEW

File: app/src/main/java/org/mozilla/rocket/content/travel/domain/GetCityWikiUseCase.kt [hunk 1]
```diff
@@ -24,12 +24,12 @@ fun String.trimContentWithinParentheses(): String {
 
     val trimmed = this.filter {
 
-        if (it.equals('(')) {
+        if (it.equals('(') || it.equals('（')) {
```
Comment (benjamin-cheng) [inline app/src/main/java/org/mozilla/rocket/content/travel/domain/GetCityWikiUseCase.kt]: `it.equals('（')` and others can be simplified to `it == '（'`. It's not a merge blocker.
