### PR TITLE
Show download complete SnackBar in private mode. Closes #3070

### LINKED ISSUE #3070: Can not see image downloaded snack bar in private mode
**Steps To Reproduce**
1. launch app 
2. open private mode
3. long click any image 
3. click [save image]

**Expected behavior**
ask for access permission, show snack bar [file donwloaded] and [open]

**Actual behavior**
not show  snack bar, only notification shows downloaded image completed

**Device info (please complete the following information):**
 - Pixel 2 (9.0)
 - Redmi 4X (7.1.2)
 - Vivo 1606 (6.0.1)

**Reproduce rate**
10/10

### PR DESCRIPTION
**Pull request by josephyu1110**

### CODE REVIEW

File: app/src/main/java/org/mozilla/rocket/privately/PrivateModeActivity.kt [hunk 1]
```diff
@@ -42,6 +55,32 @@ class PrivateModeActivity : BaseActivity(),
     private lateinit var tabViewProvider: PrivateTabViewProvider
     private lateinit var sharedViewModel: SharedViewModel
     private lateinit var screenNavigator: ScreenNavigator
+    private val downloadCompleteReceiver = object : BroadcastReceiver() {
+        override fun onReceive(context: Context, intent: Intent) {
+            val downloadId = intent.getLongExtra(DownloadManager.EXTRA_DOWNLOAD_ID, -1)
+
+            Thread(Runnable {
```
Comment (cnevinc) [inline app/src/main/java/org/mozilla/rocket/privately/PrivateModeActivity.kt]: make this local broadcastreceiver a general purpose one like
https://github.com/mozilla-tw/FirefoxLite/commit/cca8521f9ede4c3c3de8a00f7f748db4d3c43848

use ThreadUtil for bg thread work, and then add comment to replace this with lifecycle aware coroutine.

File: app/src/main/java/org/mozilla/rocket/privately/browse/BrowserFragment.kt [hunk 2]
```diff
@@ -377,11 +379,18 @@ class BrowserFragment : LocaleAwareFragment(),
         override fun onDownloadStart(download: Download) {
             if (!TextUtils.isEmpty(download.url)) {
                 val cookie = CookieManager.getInstance().getCookie(download.getUrl())
+                val fileName: String?
```
Comment (cnevinc) [inline app/src/main/java/org/mozilla/rocket/privately/browse/BrowserFragment.kt]: is fileName nullable?
maybe fileName?.let{
//  move DownloadManager.Request....code here?
}

**Comment by cnevinc** [comment]
need to think about permission handling separately.

Since it's another process, the permission may not be synced.

**Comment by josephyu1110** [comment]
This PR only fixes the snackbar is not showed when download complete in private mode. Download permission handling is fixed in another [PR](https://github.com/mozilla-tw/FirefoxLite/pull/3156).

File: app/src/main/java/org/mozilla/rocket/privately/PrivateModeActivity.kt [hunk 3]
```diff
@@ -206,4 +234,46 @@ class PrivateModeActivity : BaseActivity(),
...
+        uiMessageReceiver = object : BroadcastReceiver() {
+            override fun onReceive(context: Context, intent: Intent) {
+                if (intent.action == Constants.ACTION_NOTIFY_RELOCATE_FINISH) {
+                        showOpenSnackBar(intent.getLongExtra(Constants.EXTRA_ROW_ID, -1))
+                }
+            }
+        }
+    }
+
+    // TODO consider to combine with MainActivity.showOpenSnackBar()
```
Comment (cnevinc) [inline app/src/main/java/org/mozilla/rocket/privately/PrivateModeActivity.kt]: Could you do it in this PR? Otherwise we'll have two copy of the code with the same logic

File: app/src/main/java/org/mozilla/rocket/privately/PrivateModeActivity.kt [hunk 4]
```diff
@@ -206,4 +234,45 @@ class PrivateModeActivity : BaseActivity(),
...
+                // Set the open action only if we can.
+                if (existInDownloadManager) {
+                    snackbar.setAction(R.string.open) { _ -> IntentUtils.intentOpenFile(this, downloadInfo.fileUri, downloadInfo.mimeType) }
+                }
+                snackbar.show()
+            }
+        }
+    }
+
+    private fun logOrCrash(message: String) {
```
[the remark this answers is not in the document]
Comment (josephyu1110) [reply app/src/main/java/org/mozilla/rocket/privately/PrivateModeActivity.kt]: Use LoggerWrapper instead.

File: app/src/main/java/org/mozilla/rocket/privately/PrivateModeActivity.kt (hunk 3 above)
Comment (josephyu1110) [reply app/src/main/java/org/mozilla/rocket/privately/PrivateModeActivity.kt]: Move to ViewUtils.

File: app/src/main/java/org/mozilla/focus/download/DownloadInfoManager.java [hunk 5]
```diff
@@ -320,6 +325,28 @@ public DownloadManager getDownloadManager() {
...
+    public void showOpenDownloadSnackBar(final Long rowId, @NonNull final View container, final String logTag) {
+        queryByRowId(rowId, downloadInfoList -> {
+            final boolean existInLocalDB = downloadInfoList.size() > 0;
+            if (!existInLocalDB) {
+                LoggerWrapper.throwOrWarn(logTag, "Download Completed with unknown local row id");
+                return;
+            }
+            final DownloadInfo downloadInfo = downloadInfoList.get(0);
+            final boolean existInDownloadManager = downloadInfo.existInDownloadManager();
+            if (!existInDownloadManager) {
```
Comment (cnevinc) [inline app/src/main/java/org/mozilla/focus/download/DownloadInfoManager.java]: should the method be static?
otherwise why you need this check?
