### PR TITLE
notifcation needs to be expandable

### LINKED ISSUE #4636: Day 1 Notification format - notifcation needs to be expandable
**Describe the bug**
Day 1 notification in the prview mode from device -> can't open the notification to see the whole message.

**Steps To Reproduce**
1. Reset and clean data
2. Open App
3. Get Day 1 notification on the device
4. Notification show

**Expected behavior**
With the button and click the butoon to see more detail message

**Actual behavior**
NO button to extend the notification detail

**Screenshots/videos**
Screenshot_20200114_133923_org mozilla rocket beta
Screenshot_20200114_133923_org mozilla rocket beta

**Reproduce rate**
100%

### PR DESCRIPTION
**Pull request by proevan**
to fix #4636 

device-2020-03-03-121024

### CODE REVIEW

File: app/src/main/java/org/mozilla/rocket/periodic/FirstLaunchWorker.kt [hunk 1]
```diff
@@ -88,6 +97,8 @@ fun String.jsonStringToFirstrunNotification(): FirstrunNotification? {
     return try {
         val jsonObject = JSONObject(this)
         FirstrunNotification(
+            jsonObject.getString("messageId"),
+            jsonObject.optString("title"),
```
Comment (benjamin-cheng) [inline app/src/main/java/org/mozilla/rocket/periodic/FirstLaunchWorker.kt]: `title` will not be null with `optString`
