### PR TITLE
Fix private mode sanitize issue. closes #3170 closes #3171

### LINKED ISSUE #3170: When back to private home page, does not show toast msg and private browsing notification still display
**Describe the bug**
When back to private home page, does not show toast msg and private browsing notification still display

**Steps To Reproduce**
1. Reset Rocket and launch it
2. Switch to private browsing mode
3. Visit some websites 
4. Tap system Back until back to Private - Home page

**Expected behavior**
There is no browsing history in the stack.
    Remove private browsing notification 
    Show a toast to remind user.
      - Your private browsing history has been erased.

**Actual behavior**
1. Private browsing notification still display
2. Does not show the toast msg

**Screenshots/videos**
https://drive.google.com/file/d/1nqN27YU2SlIi5HL56eV1OCfrYCkzfvyq/view?usp=sharing

**Device info (please complete the following information):**
 - Device: Samsung S8
 - OS: Android 8.0.0
 - Webview: 72.0.3626.105
 - Version: Lite 1.1.0 (10022)

**Reproduce rate**
3/3

**Additional context**
N/A

### put correct labels ###
S2

### LINKED ISSUE #3171: Tap trash icon in private mode, does not show toast msg and private browsing notification still display
**Describe the bug**
Tap trash icon in private mode, does not show toast msg and private browsing notification still display

**Steps To Reproduce**
1 Launch Rocket
2 Switch to private mode
3 Open a website 
4 Tap trash icon 

**Expected behavior**
4. Toast message is shown with the message: Your private browsing history has been erased
 4.1 back to main private page
 4.2 notification icon disappears

**Actual behavior**
1. Does not show the toast msg
2. Private browsing notification still display

**Screenshots/videos**
https://drive.google.com/file/d/1Nt4gX_fcl-l3hFSAg18Qod7WOwJIG7id/view?usp=sharing

**Device info (please complete the following information):**
* Device: Samsung S8
* OS: Android 8.0.0
* Webview: 72.0.3626.105
* Version: Lite 1.1.0 (10022)

**Reproduce rate**
3/3

**Additional context**
N/A

### put correct labels
S2

### PR DESCRIPTION
**Pull request by cnevinc**

### CODE REVIEW

File: app/src/main/java/org/mozilla/rocket/privately/browse/BrowserFragment.kt [hunk 1]
```diff
@@ -249,6 +249,7 @@ class BrowserFragment : LocaleAwareFragment(),
 
         sessionManager.dropTab(focus.id)
         ScreenNavigator.get(activity).popToHomeScreen(true)
+        listener?.onNotified(this, TYPE.DROP_BROWSING_PAGES, null)
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/rocket/privately/browse/BrowserFragment.kt]: Consider writing a function sanitize that reuses onDeleteClicked() or call onDeleteClicked itself directly.

Comment (cnevinc) [reply app/src/main/java/org/mozilla/rocket/privately/browse/BrowserFragment.kt]: More refactoring coming up. Will do that there.
