### PR TITLE
fix passing null view as a target view to show onboarding spotlight

### LINKED ISSUE #4766: 2.1.10 Got 4 new Crashes on HomeFragment
**Additional context**
We find 4 new crash on 2.1.10 for HomeFragmet. Since it has low crashes as low user installations, I will keep monitoring it. However we still need investigate the root cause.
Need Action:  Need dev team investigate root cause.
1. https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/b750f466b4d14137264234a8d4b7f40d?time=last-seven-days&sessionId=5E5659F203B700013B163DD223703215_DNE_0_v2
2. https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/7736613db04bc5025e37f92e06777c71?time=last-seven-days&sessionId=5E56C4D9015F00015F18BB97614CFF15_DNE_0_v2
3. https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/fc19d48235ecd6dbab28299e6bf652a2?time=last-seven-days&sessionId=5E56AB1301BA0001516BBF1D5BD919B6_DNE_0_v2
4. https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/b750f466b4d14137264234a8d4b7f40d?time=last-seven-days&sessionId=5E5659F203B700013B163DD223703215_DNE_0_v2

### PR DESCRIPTION
**Pull request by proevan**
to fix #4766

### CODE REVIEW

File: app/src/main/java/org/mozilla/rocket/home/HomeFragment.kt [hunk 1]
```diff
@@ -533,14 +538,17 @@ class HomeFragment : LocaleAwareFragment(), ScreenNavigator.HomeScreen {
     }
 
     private fun showRequestClickContentHubOnboarding(couponName: String) {
-        activity?.let {
-            content_hub.post {
+        val dismissListener = DialogInterface.OnDismissListener {
+            if (isAdded) {
+                restoreStatusBarColor()
```
Comment (benjamin-cheng) [inline app/src/main/java/org/mozilla/rocket/home/HomeFragment.kt]: Should we always try to restore status bar color if possible? I found there are null protections in `restoreStatusBarColor()`
